<a href="https://colab.research.google.com/github/AllaYermilko/DTA-2026/blob/main/homework/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [1]:
import numpy as np

# Твій код:
# Створи NumPy масив із цих значень і назви його temps
# Виведи масив
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print("Середньомісячні температури у Харкові:", temps, "\n")

# Виведи: кількість вимірів (ndim), форму (shape), кількість елементів (size), тип даних (dtype)
print(temps.ndim)
print(temps.shape)
print(temps.size)
print(temps.dtype,"\n")

# Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)
print("Середньорічна температура:   ", temps.mean().round(1))
print("Мінімальна температура:      ", temps.min().round(1))
print("Максимальна температура:     ", temps.max().round(1))

Середньомісячні температури у Харкові: [-5 -4  2 10 17 21 23 22 16  9  2 -3] 

1
(12,)
12
int64 

Середньорічна температура:    9.2
Мінімальна температура:       -5
Максимальна температура:      23


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [ ]:
# Твій код:

# Створи матрицю plan розміром 3×4, заповнену значенням 50 (тис. грн) — використай np.full(). Виведи матрицю
plan = np.full((3, 4), 50000)
print(plan, "\n")

# Виведи її форму та загальну кількість елементів
print("Форма: ", plan.shape)
print("Загальна кількість елементів:", plan.size, "\n")

# Створи другу матрицю bonus розміром 3×4 із нулів — менеджери ще не отримали бонусів
bonus = np.zeros((3, 4))
print(bonus, "\n")

# Виведи суму plan + bonus і переконайся що вона рівна plan
print((plan + bonus) == plan)

[[50000 50000 50000 50000]
 [50000 50000 50000 50000]
 [50000 50000 50000 50000]] 

Форма:  (3, 4)
Загальна кількість елементів: 12 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [ ]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
print("Продажі першого тижня (дні 1–7):", sales[:7])
print("Продажі другого тижня (дні 8–14):", sales[7:])
print("Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день:", sales[[5,6,12,13]])
print("Продажі через день:", sales[1::2])
print("Масив у зворотному порядку:", sales[::-1])

Продажі першого тижня (дні 1–7): [320 415 290 480 350 620 580]
Продажі другого тижня (дні 8–14): [310 440 305 510 370 650 595]
Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день: [620 580 650 595]
Продажі через день: [415 480 620 310 305 370 595]
Масив у зворотному порядку: [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [ ]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
# Виведи всі оцінки Олени (перший рядок)
print("Оцінки Олени:", grades[0])

# Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
print("Оцінки всіх студентів з 3-го предмету:", grades[:,2])

# Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
print("Підматриця оцінки Максима та Ані з предметів 2–4:\n", grades[1:3, 1:4],"\n")

# Виведи оцінки останнього студента з останнього предмету
print("Оцінки Богдана з останнього предмету:", grades[3,4])


Оцінки Олени: [85 72 91 78 88]
Оцінки всіх студентів з 3-го предмету: [91 74 82 68]
Підматриця оцінки Максима та Ані з предметів 2–4:
 [[88 74 95]
 [65 82 70]] 

Оцінки Богдана з останнього предмету: 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [ ]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
# Переведи ціни в гривні (курс: 1 USD = 41.5 UAH), результат округли до 2 знаків
prices_uah = prices_usd * 41.5
print("Ціни в гривнях:", prices_uah.round(2))

# Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
prices_vat_uah = prices_uah * 1.2
print("З ПДВ (20%):", prices_vat_uah.round(2), "\n")

# Знайди: мінімальну, максимальну, середню ціну з ПДВ
print("Середня ціна з ПДВ:          ", prices_vat_uah.mean().round(2), "грн")
print("Мінімальна ціна з ПДВ:       ", prices_vat_uah.min(), "грн")
print("Максимальна ціна з ПДВ:      ", prices_vat_uah.max(), "грн", "\n")

# Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
print("Загальна вартість кошика:    ", prices_vat_uah.sum().round(2), "грн")

Ціни в гривнях: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
З ПДВ (20%): [ 796.3  2116.5   398.4  6225.   1680.75 3346.56  497.5 ] 

Середня ціна з ПДВ:           2151.57 грн
Мінімальна ціна з ПДВ:        398.4 грн
Максимальна ціна з ПДВ:       6225.0 грн 

Загальна вартість кошика:     15061.01 грн


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [ ]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
# Порахуй загальну вартість кожного товару на складі (quantity * cost_each)
total_value = quantity * cost_each
print("Загальна вартість кожного товару:", total_value)

# Знайди загальну вартість всього складу
print("Загальна вартість всього складу:", total_value.sum(), "грн")

# Знайди товар з найбільшою сумарною вартістю — використай np.argmax()
best_product = np.argmax(total_value)
print(f"Товар з найбільшою сумарною вартістю: {names[best_product]} з сумою {total_value[best_product]} грн")

# Знайди товар з найменшою сумарною вартістю — np.argmin()
weak_product = np.argmin(total_value)
print(f"Товар з найменшою сумарною вартістю: {names[weak_product]} з сумою {total_value[weak_product]} грн")

# Виведи середню вартість одного найменування на складі
print("Середня вартість одного найменування на складі:", cost_each.mean().round(2), "грн")

Загальна вартість кожного товару: [ 30000  81000  13500 171000  28500  24000  45000]
Загальна вартість всього складу: 393000 грн
Товар з найбільшою сумарною вартістю: Монітор з сумою 171000 грн
Товар з найменшою сумарною вартістю: Зошит з сумою 13500 грн
Середня вартість одного найменування на складі: 1835.0 грн


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [ ]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
# Знайди всі замовлення, виконані вчасно (≤ 30 хв)
in_time = delivery_time[delivery_time <= 30]
print("Замовлення, виконані вчасно (≤ 30 хв):", in_time)

# Знайди всі запізнілі замовлення (> 30 хв)
delayed = delivery_time[delivery_time > 30]
print("Запізнілі замовлення (> 30 хв):", delayed)

# Порахуй кількість вчасних і запізнілих
print("кількість вчасних замовлень:   ", in_time.size)
print("кількість запізнілих замовлень:", delayed.size)

# Знайди відсоток запізнілих замовлень (округли до 1 знаку)
percent_delayed = round((delayed.size / delivery_time.size) * 100, 1)
print("Bідсоток запізнілих замовлень:", percent_delayed, "%")

# Яка середня затримка серед запізнілих замовлень?
avg_delay = delayed.mean()
print("Cередня затримка серед запізнілих замовлень:", avg_delay.round(), "хв")

Замовлення, виконані вчасно (≤ 30 хв): [22 28 19 27 24 26 18 29 23 20]
Запізнілі замовлення (> 30 хв): [35 41 55 33 48 31 52 38 44 36]
кількість вчасних замовлень:    10
кількість запізнілих замовлень: 10
Bідсоток запізнілих замовлень: 50.0 %
Cередня затримка серед запізнілих замовлень: 41.0 хв


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [ ]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
# Знайди дні з продажами вище середнього за місяць
print("Щоденних продажів за місяць: ", daily, "\n")
good_sales = daily[daily > daily.mean()]
print("Дні з продажами вище середнього за місяць: ", good_sales)

# Порахуй скільки таких днів
print("Кількість днів з продажами вище середнього за місяць: ", good_sales.size, "\n")

# За допомогою np.where() створи масив status:
# 'Гарний день' — якщо продажі вище середнього
# 'Звичайний день' — якщо нижче або рівно

status = np.where(daily > daily.mean(), "Гарний день", "Звичайний день")
print(status, "\n")

# Виведи перші 10 днів: продажі та їх статус поряд
for i in range(10):
    print(f"День {i + 1}: Продажі = {daily[i]} -> {status[i]}")

Щоденних продажів за місяць:  [202 535 370 206 171 800 120 714 221 566 314 430 558 187 472 199 763 230
 761 408 869 443 591 513 485 291 376 260 559 413] 

Дні з продажами вище середнього за місяць:  [535 800 714 566 558 472 763 761 869 443 591 513 485 559]
Кількість днів з продажами вище середнього за місяць:  14 

['Звичайний день' 'Гарний день' 'Звичайний день' 'Звичайний день'
 'Звичайний день' 'Гарний день' 'Звичайний день' 'Гарний день'
 'Звичайний день' 'Гарний день' 'Звичайний день' 'Звичайний день'
 'Гарний день' 'Звичайний день' 'Гарний день' 'Звичайний день'
 'Гарний день' 'Звичайний день' 'Гарний день' 'Звичайний день'
 'Гарний день' 'Гарний день' 'Гарний день' 'Гарний день' 'Гарний день'
 'Звичайний день' 'Звичайний день' 'Звичайний день' 'Гарний день'
 'Звичайний день'] 

День 1: Продажі = 202 -> Звичайний день
День 2: Продажі = 535 -> Гарний день
День 3: Продажі = 370 -> Звичайний день
День 4: Продажі = 206 -> Звичайний день
День 5: Продажі = 171 -> Звичайний день
День 6:

---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [ ]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
# Перетвори масив у матрицю 6×4 (6 блоків по 4 години) і виведи
matrix_6x4 = hourly.reshape(6, 4)
print("Matrix n6×4:\n", matrix_6x4, "\n")

# Знайди суму продажів у кожному 4-годинному блоці (по рядках).
print("Сума продажів у кожному 4-годинному блоці:", matrix_6x4.sum(axis=1), "\n")

# Відсортуй вихідний 1D масив за зростанням і виведи
print("Відсортований масив (↑):  ", np.sort(hourly), "\n")

# Знайди індекси годин відсортованих за зростанням продажів — np.argsort()
print("Індекси сортування годин: ", np.argsort(hourly), "\n")

# Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)
top3 = np.sort(hourly)[-3:]
print("Топ-3:", top3, "\n")

Matrix n6×4:
 [[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]] 

Сума продажів у кожному 4-годинному блоці: [ 28  66 235 240 257 112] 

Відсортований масив (↑):   [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74] 

Індекси сортування годин:  [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18] 

Топ-3: [68 70 74] 



---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [15]:
# Твій код:
# 1. Встанови np.random.seed(99)
np.random.seed(99)

# 2. Згенеруй масив ages — вік 50 клієнтів: цілі числа від 18 до 65
ages = np.random.randint(18, 66, size=50)
print("Вік клієнтів:\n",ages, "\n")

# 3. Згенеруй масив scores — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
scores = np.round(np.random.normal(loc=7, scale=1.5, size=50), 1)
print("Оцінки задоволеності:\n", scores, "\n")

# 4. Обріж scores так щоб значення були від 1 до 10 — np.clip(arr, 1, 10)
scores_clip = np.clip(scores, 1, 10)
print("Оцінки задоволеності від 1 до 10:\n",scores_clip, "\n")

# 5. Виведи:
# - середній вік клієнтів
mean_age = np.mean(ages)
print(f"• Середній вік клієнтів: {mean_age:.1f} років")

# - середню оцінку задоволеності
mean_score = np.mean(scores)
print(f"• Середня оцінка задоволеності: {mean_score:.2f}")

# - кількість клієнтів з оцінкою >= 8 («задоволені»)
satisfied_count = np.sum(scores >= 8)
print(f"• Кількість клієнтів з оцінкою >= 8 («задоволені»): {satisfied_count}")

# - відсоток задоволених
satisfied_percentage = (satisfied_count / 50) * 100
print(f"• Відсоток задоволених: {satisfied_percentage:.1f}%")


Вік клієнтів:
 [19 53 58 27 58 36 22 23 19 41 53 19 47 56 61 41 20 18 30 58 26 38 57 33
 65 45 55 64 54 62 35 27 50 39 65 59 53 37 40 44 23 30 50 45 19 62 29 29
 47 49] 

Оцінки задоволеності:
 [ 5.7  6.4  5.7  9.2  5.5  6.1  6.8  7.9  4.8  8.8  7.5  6.4  7.2  6.2
  6.7  7.4  6.   4.7  7.1  5.   5.4  5.6  8.   8.5  9.1  9.6  7.1  7.1
  7.4  7.8  6.7  7.1  7.3  5.5  6.7  5.5  7.9  8.3  4.9  6.2 11.1  4.8
  7.6  4.7  6.5  4.2  7.7  7.7  9.4  8. ] 

Оцінки задоволеності від 1 до 10:
 [ 5.7  6.4  5.7  9.2  5.5  6.1  6.8  7.9  4.8  8.8  7.5  6.4  7.2  6.2
  6.7  7.4  6.   4.7  7.1  5.   5.4  5.6  8.   8.5  9.1  9.6  7.1  7.1
  7.4  7.8  6.7  7.1  7.3  5.5  6.7  5.5  7.9  8.3  4.9  6.2 10.   4.8
  7.6  4.7  6.5  4.2  7.7  7.7  9.4  8. ] 

• Середній вік клієнтів: 41.8 років
• Середня оцінка задоволеності: 6.89
• Кількість клієнтів з оцінкою >= 8 («задоволені»): 10
• Відсоток задоволених: 20.0%


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [16]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [21]:
# Твій код:
# Загальна виручка за 56 днів
print("Загальна виручка за 56 днів: ", sales_56.sum().round(2), "грн")

# Середньоденна виручка (округли до 2 знаків)
print("Середньоденна виручка:       ", sales_56.mean().round(2), "грн")

# Мінімальний та максимальний денний продаж
print("Мінімальний денний продаж:   ", sales_56.min().round(2), "грн")
print("Максимальний денний продаж:  ", sales_56.max().round(2), "грн")

# Стандартне відхилення (наскільки продажі «скачуть»)
sales_std = np.std(sales_56)
print("Стандартне відхилення:       ", sales_std.round())

Загальна виручка за 56 днів:  31819 грн
Середньоденна виручка:        568.2 грн
Мінімальний денний продаж:    222 грн
Максимальний денний продаж:   1072 грн
Стандартне відхилення:        196.0


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [30]:
# Твій код:
# Перетвори sales_56 у матрицю 8×7 (8 тижнів по 7 днів)
matrix_8x7 = sales_56.reshape(8, 7)
print("Matrix n8×7:\n", matrix_8x7, "\n")

# Знайди виручку кожного тижня (сума по рядках)
print("Виручка кожного тижня:", matrix_8x7.sum(axis=1))

# Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
print("Найкращий тиждень: №", np.argmax(matrix_8x7.sum(axis=1)) + 1)
print(f"Сума продажів за цей тиждень:", np.max(matrix_8x7.sum(axis=1)))

# Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
print("Середня виручка по днях тижня:", matrix_8x7.mean(axis=0))

# Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)
print("Найприбутковіший день тижня:", np.argmax(matrix_8x7.mean(axis=0)))


Matrix n8×7:
 [[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]] 

Виручка кожного тижня: [4555 3921 3563 3546 5036 3300 4228 3670]
Найкращий тиждень: № 5
Сума продажів за цей тиждень: 5036
Середня виручка по днях тижня: [520.375 455.5   565.875 607.75  463.75  629.75  734.375]
Найприбутковіший день тижня: 6


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [32]:
# Твій код:
# Знайди кількість «слабких» днів — продажі нижче 400 грн
weak_days = np.sum(sales_56 < 400)
print("Кількість «слабких» днів:", weak_days)

# Знайди кількість «сильних» днів — продажі вище 700 грн
strong_days = np.sum(sales_56 > 700)
print("Кількість «сильних» днів:", strong_days, "\n")

# Яка середня виручка у слабкі дні і яка у сильні?
print("Середня виручка у слабкі дні:", sales_56[sales_56 < 400].mean().round(2))
print("Середня виручка у сильні дні:", sales_56[sales_56 > 700].mean().round(2), "\n")

# Створи масив labels за допомогою np.where():
# 'Слабкий' якщо < 400
# 'Сильний' якщо > 700
# 'Нормальний' в решті випадків (підказка: вкладений np.where)
labels = np.where(sales_56 < 400, 'Слабкий',
         np.where(sales_56 > 700, 'Сильний', 'Нормальний'))

print("labels:\n", labels, "\n")

# Виведи перші 14 днів: продажі та їх мітки
for i in range(14):
    print(f"День {i + 1}: Продажі = {sales_56[i]} -> {labels[i]}")







Кількість «слабких» днів: 12
Кількість «сильних» днів: 19 

Середня виручка у слабкі дні: 302.0
Середня виручка у сильні дні: 785.16 

labels:
 ['Сильний' 'Сильний' 'Сильний' 'Нормальний' 'Слабкий' 'Нормальний'
 'Сильний' 'Нормальний' 'Слабкий' 'Нормальний' 'Нормальний' 'Сильний'
 'Нормальний' 'Сильний' 'Нормальний' 'Нормальний' 'Нормальний'
 'Нормальний' 'Сильний' 'Нормальний' 'Нормальний' 'Слабкий' 'Слабкий'
 'Слабкий' 'Сильний' 'Слабкий' 'Нормальний' 'Сильний' 'Сильний'
 'Нормальний' 'Сильний' 'Сильний' 'Нормальний' 'Сильний' 'Сильний'
 'Слабкий' 'Слабкий' 'Нормальний' 'Нормальний' 'Слабкий' 'Сильний'
 'Нормальний' 'Нормальний' 'Нормальний' 'Сильний' 'Нормальний' 'Слабкий'
 'Сильний' 'Сильний' 'Нормальний' 'Нормальний' 'Слабкий' 'Слабкий'
 'Нормальний' 'Сильний' 'Нормальний'] 

День 1: Продажі = 706 -> Сильний
День 2: Продажі = 739 -> Сильний
День 3: Продажі = 748 -> Сильний
День 4: Продажі = 646 -> Нормальний
День 5: Продажі = 383 -> Слабкий
День 6: Продажі = 556 -> Нормальний
День

---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
